
############################################## USER Controller ##############################################

### Test route
GET http://localhost:4001/test/users/test
Content-Type: application/json
###
### GET-Get all users
GET http://localhost:4001/test/users/getAll
Content-Type: application/json
###
### GET-Get single user
GET http://localhost:4001/test/users/test@email.com
Content-Type: application/json
###
### POST-Create new user
POST http://localhost:4001/test/users/create
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test password",
  "name": "test name",
  "surname": "test name",
  "phone": "test phone",
  "birthDate": "2001-01-01"
}
###
### PATCH-Update user
PATCH http://localhost:4001/test/users/update/test@test.com
Content-Type: application/json

{
  "name": "test name MODIFIED 1",
  "surname": "test MODIFIED 1"
}
###
### DELETE-Delete user
DELETE http://localhost:4001/test/users/delete/test1@test.com
Content-Type: application/json
###

### GET-Get password
GET http://localhost:4001/test/users/password/test@email.com
Content-Type: application/json
###

############################################## REFRESH TOKEN CONTROLLER
### Test route
GET http://localhost:4001/test/refreshtokens/test
Content-Type: application/json
###
### GET-Get all REFRESH TOKENS
GET http://localhost:4001/test/refreshtokens/getAll
Content-Type: application/json
###
### GET-Get single REFRESH TOKEN
GET http://localhost:4001/test/refreshtokens/test1@test.com
Content-Type: application/json
###
### POST-Create new refresh token
POST http://localhost:4001/test/refreshtokens/create
Content-Type: application/json

{
  "email": "test@test.com"
}
###
### DELETE- Delete refresh token
DELETE http://localhost:4001/test/refreshtokens/delete/test1@test.com
Content-Type: application/json
###

############################################## SYSTEM CONTROLLER
### Test route
GET http://localhost:4001/test/system/test
Content-Type: application/json
###
### POST-Sign up new user
POST http://localhost:4001/test/system/signup
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "test password",
  "name": "test name",
  "surname": "test name",
  "phone": "test phone",
  "birthDate": "2001-01-01"
}
###
### POST-Sign in user
POST http://localhost:4001/test/system/signin
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "test password"
}
###
### POST-Sign out user
POST http://localhost:4001/test/system/signout/test1@test.com
Content-Type: application/json
Authorization: Bearer tokenValue

###

### POST-Generate New Access Token
POST http://localhost:4001/test/system/generatenewaccesstoken
Content-Type: application/json

{
  "email": "test1@test.com",
  "refreshtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdDFAdGVzdC5jb20iLCJuYW1lIjoidGVzdCBuYW1lIiwic3VybmFtZSI6InRlc3QgbmFtZSIsImJpcnRoRGF0ZSI6IjIwMDEtMDEtMDEiLCJwaG9uZSI6InRlc3QgcGhvbmUiLCJjb3VudHJ5IjoiVXJ1Z3VheSJ9LCJpYXQiOjE2NjE2MzY5OTIsImV4cCI6MTY2NDIyODk5Mn0.Ag0Bg4rDJw1cNl-IZxYviMPuxwp7xovOU_CBSyO5Jt8"
}
###

